name: Gradle CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    name: Gradle-Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew buildPlugin
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiraiHTTPCat
          path: build/mirai/mirai-httpcat-*.mirai2.jar
          if-no-files-found: error
